name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build black flake8 pytest
    - name: Lint
      run: |
        python -m black --check . && flake8 .
    - name: Build package
      run: |
        python -m build
    - name: Install built package and test
      run: |
        pip install dist/*.whl
        pytest
